version: "3.7"

services:
  service-a:
    build:
      context: .
      dockerfile: a/Dockerfile
    privileged: true
    entrypoint:
      - dockerize
      - -timeout
      - 300s
      - -wait
      - tcp://mysql:3306
    command: ./main
    ports:
      - "8011:8011"
    restart: always
    depends_on:
      - mysql

  service-b:
    build:
      context: .
      dockerfile: b/Dockerfile
    privileged: true
    ports:
      - "8022:8022"
    restart: always

  mysql:
    image: bitnami/mysql:5.7.25
    volumes:
      - ./mysql/my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: "test_r00t"
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass_hoge
      BITNAMI_DEBUG: "true"

  newman:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    entrypoint:
      - dockerize
      - -timeout
      - 300s
      - -wait
      - tcp://service-a:8011
      - -wait
      - tcp://service-b:8022
    volumes:
      - ./e2e:/etc/newman/e2e
