version: "3.7"

services:
  service-a:
    build:
      context: .
      dockerfile: a/Dockerfile
    privileged: true
    ports:
      - "8011:8011"
    restart: always
    depends_on:
      - mysql

  service-b:
    build:
      context: .
      dockerfile: b/Dockerfile
    privileged: true
    ports:
      - "8022:8022"
    restart: always

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ADMIN
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass_hoge
      BITNAMI_DEBUG: "true"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  newman:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    entrypoint:
      - dockerize
      - -timeout
      - 300s
      - -wait
      - tcp://service-a:8080
      - -wait
      - tcp://service-b:8080
    volumes:
      - ./e2e:/etc/newman/e2e
