# This is a basic workflow to help you get started with Actions

name: Newman Example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker-compose up -d
      - name: Run E2E
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
          POSTMAN_ENVIRONMENT_ID: ${{ secrets.POSTMAN_ENVIRONMENT_ID }}
        run:
          curl -H 'X-Api-Key:' https://api.getpostman.com/collections/"$POSTMAN_COLLECTION_ID" > e2e/api.json \
          curl -H 'X-Api-Key:' https://api.getpostman.com/environments/"$POSTMAN_ENVIRONMENT_ID" > e2e/e2e.postman_environment.json \
          docker-compose run newman newman run e2e/api.json --environment=e2e/e2e.postman_environment.json
